name: CI for Streamlit Chatbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정 (3.10)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pytest 실행
        run: |
          pytest --maxfail=5 --disable-warnings --tb=short
